import type { Metadata } from "next";
import "./globals.css";
import localFont from 'next/font/local'

const aurea_bold = localFont({
  src: '../../public/fonts/aurea-bold.woff2',
  variable: '--font-aurea-bold',
  display: "swap"
})

const aurea_regular = localFont({
  src: '../../public/fonts/aurea-regular.woff2',
  variable: '--font-aurea-regular',
  display: "swap"
})

const aurea_ultra_roman = localFont({
  src: '../../public/fonts/aureaultra-roman.woff2',
  variable: '--font-aurea-ultra-roman',
  display: "swap"
})

const aeonik = localFont({
  src: '../../public/fonts/Aeonik-Regular.otf',
  variable: '--font-aeonik',
  display: "swap"
})


export const metadata: Metadata = {
  title: "Iquine",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={aurea_ultra_roman.variable}>
      <body>{children}</body>
    </html>
  );
}
